services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image đặt tên nội bộ nếu thích (không pull từ registry)
    image: motel-manager:local
    ports:
      - 9090:80
    restart: unless-stopped
